#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint
# yarn lint-staged

AUTHORS=(
  'DuyLinh Dang:duylinhdang1998@gmail.com'
)
AUTHOR_CONFIG="$GIT_AUTHOR_NAME:$GIT_AUTHOR_EMAIL"

if [[ ! " ${AUTHORS[*]} " =~ " ${AUTHOR_CONFIG} " ]]; then
  echo ⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫
  echo "Your name should be the same as your username."
  echo "Example: Mason Le <lhngoc2497@gmail.com>"
  echo
  echo "Fix your username by using:"
  echo "git config user.name YourName"
  echo "git config user.email YourEmail"
  echo "Then try commiting again"
  echo ⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫
  exit 1
fi